server:
  port: 8007

spring:
  application:
    name: Users

  datasource:
    url: jdbc:postgresql://localhost:5432/ilerijava
    username: devuser
    password: devpassword
    default_schema: users_application

  flyway:
    default-schema: users_application

  jpa:
    hibernate:
      ddl-auto: validate

  services:
    gateway: http://192.168.137.149:8001       # Gateway Servisi
    product: http://192.168.137.35:8002       # Ürün Servisi
    order: http://192.168.137.169:8003         # Sipariş Servisi
    notification: http://192.168.137.111:8004   # Bildirim Servisi
    cart: http://192.168.137.244:8005          # Alışveriş Sepeti Servisi
    payment: http://192.168.137.52:8006       # Ödeme Servisi
    user: http://192.168.137.195:8007          # Kullanıcı Servisi
    invoice: http://192.168.137.140:8008       # Fatura Servisi
    shipment: http://192.168.137.179:8011      # Kargo Servisi

  springdoc:
    api-docs:
      path: /api-docs
