server:
  port: 8007

spring:
  application:
    name: Users

  datasource:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    default_schema: users_application

  flyway:
    locations: classpath:DB/Migrations
    schemas: users_application
    default-schema: users_application
    enabled: true
    createSchemas: false

  jpa:
    hibernate:
      ddl-auto: none
	  
	  services:
	    gateway: http://localhost:8001       # Gateway Servisi
	    product: http://localhost:8002       # Ürün Servisi
	    order: http://localhost:8003         # Sipariş Servisi
	    notification: http://localhost:8004   # Bildirim Servisi
	    cart: http://localhost:8005          # Alışveriş Sepeti Servisi
	    payment: http://localhost:8006       # Ödeme Servisi
	    user: http://localhost:8007          # Kullanıcı Servisi
		invoice: http://localhost:8008       # Fatura Servisi
	    shipment: http://localhost:8011      # Kargo Servisi

